"""Change sender column to VARCHAR from native ENUM

Revision ID: 9b797a718f53
Revises: 20a577ba5a31
Create Date: 2025-05-02 14:07:46.601886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b797a718f53'
down_revision: Union[str, None] = '20a577ba5a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender',
               existing_type=postgresql.ENUM('USER', 'BOT', name='sendertype'),
               type_=sa.Enum('USER', 'BOT', name='sendertype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender',
               existing_type=sa.Enum('USER', 'BOT', name='sendertype', native_enum=False),
               type_=postgresql.ENUM('USER', 'BOT', name='sendertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
